### ISSUE TITLE
Whitespace bug

### ISSUE THREAD

**Issue by Benny1988** [Wouter-Berman/Generate-CSR#4]
Hello Wouter,

the whitespace bug still exists. I downloaded the latest version, but there are same whitespaces like before.

Can u fix this? 

Kind regards

**Comment by Benny1988** [comment]
Do you know what i mean? :)

**Comment by Wouter-Berman** [comment]
Hi Benny,
This is the first time I hear about a whitespace bug. And no, I do not know what you mean. Could you elaborate?
Kind regards,
Wouter.
